# Generated by Django 5.2.1 on 2025-05-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_annonce_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='localisation',
            field=models.CharField(default='Casablanca', max_length=255),
        ),
    ]
