# Generated by Django 5.2.1 on 2025-05-26 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_categorie_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='annonce',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ann', to='App.annonce'),
        ),
    ]
