# Generated by Django 5.2.1 on 2025-05-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_question_annonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
