# Generated by Django 5.2.1 on 2025-05-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_administrateur_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
