# Generated by Django 5.2.1 on 2025-05-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_annonce_localisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='image',
            field=models.ImageField(max_length=255, upload_to='admin/'),
        ),
    ]
