# Generated by Django 5.2.1 on 2025-05-24 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_favoris'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='App.categorie'),
        ),
    ]
